## 浏览器错误报告

所有主流桌面浏览器默认情况下，所有浏览器都会隐藏错误信息。一个原因是除了开发者之外这些信息对别人没什
么用，另一个原因是网页在正常操作中报错的固有特性。

所有现代桌面浏览器都会通过控制台暴露错误。移动浏览器不会直接在设备上提供控制台界面。Chrome 移动版和 Safari 的 iOS 版内置了实用工具，支持将设备连接到宿主操作系统中相同的浏览器。然后，就可以在对应的桌面浏览器中查看错误了。此外也可以使用第三方工具直接在移动设备上调试。Firefox 常用的调试工具是 Firebug Lite，这需要通过 JavaScript 的书签小工具向当前页面中加入 Firebug 脚本才可以。脚本运行后，就可以直接在移动浏览器上打开调试界面。Firebug Lite 也有面向其他浏览器(如 Chrome)的版本。

## 错误处理

### **try**/**catch**语句

ECMA-262 第 3 版新增了 try/catch 语句，作为在 JavaScript 中处理异常的一种方式。基本的语法 如下所示，跟 Java 中的 try/catch 语句一样: 

```
try {
 // 可能出错的代码 

} catch (error) { // 出错时要做什么 

} 
```

任何可能出错的代码都应该放到 try 块中，而处理错误的代码则放在 catch 块中。

果 try 块中有代码发生错误，代码会立即退出执行，并跳到 catch 块中。catch 块此时接收到一个对象，该对象包含发生错误的相关信息。与其他语言不同，即使在 catch 块中不使用错误对象，也必须为它定义名称。错误对象中暴露的实际信息因浏览器而异，但至少包含保存错误消息的 message属性。

} catch (error) { // 出错时要做什么 

} 

```
try {
      window.someNonexistentFunction();
    } catch (error){
      console.log(error.message);
}
```

#### **finally** 子句

try/catch 语句中可选的 finally 子句始终运行。如果 try 块中的代码运行完，则接着执行 finally 块中的代码。如果出错并执行 catch 块中的代码，则 finally 块中的代码仍执行。try 或 catch 块无法阻止 finally 块执行，包括 return 语句。 

```
function testFinally(){
	try {
    return 2;
    } catch (error){
      return 1;
    } finally {
      return 0;
  } 
 }
```

如果写出 finally 子句，catch 块就成了可选的(它们两者中只有一个是必需的)。

#### 错误类型

代码执行过程中会发生各种类型的错误。每种类型都会对应一个错误发生时抛出的错误对象。 ECMA-262 定义了以下 8 种错误类型: 

- Error  :基类型，其他错误类型继承该类型。浏览器很少会抛出 Error 类型的错误，该类型主要用于开
  发者抛出自定义错误。
- InternalError  :底层 JavaScript 引擎抛出异常时由浏览器抛出。如：递归过多导致了栈溢出
-  EvalError  ：使用 eval()函数发生异常时抛出。。ECMA-262 规定，“如果 eval 属性没有被直接调用(即没有将其名称作为一个 Identifier，也就是 CallExpression 中的MemberExpression)，或者如果 eval 属性被赋值”，就会抛出该错误。基本上，只要不把 eval()当成函数调用就会报告该错误:
- RangeError ： 在数值越界时抛出。
- ReferenceError ：在找不到对象时发生。这种错误经常是由访问不存在的变量而导致的
- SyntaxError  ：经常在给 eval()传入的字符串包含 JavaScript 语法错误时发生
- TypeError ：主要发生在变量不是预期类型，或者访问不存在的方法时，尤其是在使用类型特定的操作而变量类型不对时
- URIError ：在使用 encodeURI()或 decodeURI()但传入了格式错误的URI 时发生

不同的错误类型可用于为异常提供更多信息，以便实现适当的错误处理逻辑。在 try/catch 语句的 catch 块中，可以使用 instanceof 操作符确定错误的类型。

#### **try**/**catch** 的用法

当 try/catch 中发生错误时，浏览器会认为错误被处理了，因此就不会再使用机制报告错误。

try/catch 语句最好用在自己无法控制的错误上。